module.exports = {
    SUCCESS: "success",
    FAIL: "fail",
    ERROR: "error",
    UNDEFINED: "undefined",
    DESC: -1,
    UPDATED_AT: "updatedAt",
    CATEGORY_IMAGE_ONE: "categoryImage1",
    SUB_CATEGORYIMAGE:"SubCategoryImage",
    POST_IMAGE:"postImage",
    POST_IMAGE_ONE:"postImageOne",
    POST_IMAGE_TWO:"postImageTwo",
    NULL_STRING: "",
    NULL_ARRAY: [],
    DATA: "data ",
    IMAGE_PATH: {
        UPLOADED_CATEGORY_IMAGE: "uploaded_attachment/category_image/",
        UPLOADED_SUB_CATEGORY_IMAGE: "uploaded_attachment/sub_category_image/",
        UPLOADED_POST_IMAGE: "uploaded_attachment/post_image/",
        UPLOADED_POST_IMAGE_ONE: "uploaded_attachment/post_image_one/",
        UPLOADED_POST_IMAGE_TWO: "uploaded_attachment/post_image_two/",
    },
    MESSAGE: {
        AUTHENTICATION_TOKEN_FAIL: "Invalid token!",
        AUTH_ACCESS_FAIL: "You are not authrized person to access!",
        NO_TOKEN_PROVIDED: "No token provided!",
        REQUIRED_FIELDS_MISSING: "Required fields are missing!",
        ALREADY_EXIST: "already exist!",
        EMAIL_ALREADY_EXIST: "Email is already exist!",
        ADDED_SUCCESSFULLY: "added successfully!!!",
        IS_UPDATED_SUCCESSFULLY: "is Updated Successfully!!!",
        UPDATED_SUCCESSFULLY: "Updated Successfully!!!",
        EMAIL_INVALID: "Incorrect Email",
        INVALID_EMAIL_FORMAT: "Invalid Email Format",
        NOT_FOUND_BY_ID: "not found with ID ",
        NOT_FOUND_BY_CATEGORY_ID: "not found with category ID ",
        NOT_FOUND_BY_TYPE: "not found with product type ",
        DATA_FOUND: "Data found",
        DATA_NOT_FOUND: "Data not found",
        FOUND_SUCCESSFULLY: "found successfully!",
        DELETE_SUCCESSFULLY: "deleted successfully!",
        NOT_FOUND: "not found!",
        ERROR_OCCURRED: "Some error occurred while retrieving data",
        INVALID_PASSWORD: "Invalid password!",
        INVALID_CATEGORY_ID: "Invalid category Id!",
        INVALID_SUB_CATEGORY_ID: "Invalid  Subcategory Id!",
        INVALID_USER_ID: "Invalid  User Id!",
        INVALID_SUGGESTION_ID: "Invalid  Suggestion Id!",
        INVALID_REPORT_ID: "Invalid  Report  Id!",
        LOGIN_SUCCESS: "Login successfully!",
        FAILED_ADDED_IMAGE: "Fail to Uploaded Image!",
        FAILED_ADDED_DATA: "Fail to added Data!",
        ADDED_DATA: "request has been submitted successfully",
    },
    COLLECTION: {
        USER: "User ",
        PRODUCT:"Product ",
        CATEGORY: "category ",
        SUB_CATEGORY: " Sub category ",
        SUGGESTION: "Suggestion ",
        POST: "Post ",
        REPORT: "Report ",
        FACEBOOK: "Facebook ",
        INSTAGRAM: "Instagram ",
        TWITTER: "Twitter ",
    }
}